name: '.NET Core test'
description: 'Test projects with .NET Core'

inputs:
  target-framework:
    description: 'Target .NET framework'
    required: true
  solution:
    description: 'Solution path'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core version
      run: |
        if "${{inputs.target-framework}}" == "netcoreapp3.1"
        then
          echo "DotNetVersion=3.1.x" >> $GITHUB_ENV
        elif "${{inputs.target-framework}}" == "net5.0"
        then
          echo "DotNetVersion=5.0.x" >> $GITHUB_ENV
        else
          echo "DotNetVersion=5.0.x" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Setup .NET Core ${DotNetVersion}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${DotNetVersion}
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact-${{inputs.target-framework}}
    - name: Extract build artifact
      run: tar -xvzf build-artifact-${{inputs.target-framework}}.tar.gz
      shell: bash
    - name: Test
      run: dotnet test ${{inputs.solution}} --framework ${{inputs.target-framework}} --no-build --verbosity normal --configuration Release
      shell: bash