name: Release info

inputs:
  version-prefix:
    description: 'Overriding version prefix'
    required: false
  version-patch:
    description: 'Overriding version patch'     
    required: false
  release-type:
    description: 'Release type (dev, alpha, beta, release)'     
    required: true
    
outputs:
  version-prefix:
    description: "Version prefix"
    value: ${{ steps.version-prefix-generator.outputs.version-prefix }}
  version-suffix:
    description: "Version suffix"
    value: ${{ steps.version-suffix-generator.outputs.version-suffix }}
    
runs:
  using: "composite"
  steps:
    - id: version-prefix-generator
      env:
        default-version-prefix: 0.12.0
      run: |
        if [[ "${{ inputs.version-prefix || '' }}" != "" ]]; then
          echo "::set-output name=version-prefix::${{ inputs.version-prefix }}"
        else
          echo "::set-output name=version-prefix::${{ env.default-version-prefix }}"
        fi
      shell: bash
    - id: version-patch-setter
      env:
        default-version-patch: 1
      run: |
        if [[ "${{ inputs.version-patch || '' }}" != "" ]]; then
          echo "version-patch=${{ inputs.version-patch }}" >> $GITHUB_ENV
        else
          echo "version-patch=${{ env.default-version-patch }}" >> $GITHUB_ENV
        fi
      shell: bash
    - id: version-suffix-generator
      run: |
        if [[ "${{ inputs.release-type }}" == "release" ]]; then
          echo "::set-output name=version-suffix::"
        else
          echo "::set-output name=version-suffix::${{ inputs.release-type }}.${{ env.version-patch }}"
        fi
      shell: bash
