name: '.NET Core build'
description: 'Build projects with .NET 5'

inputs:
  target-framework:
    description: 'Target .NET framework'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x.x
    - name: Restore dependencies and build
      run: dotnet build --framework ${{inputs.target-framework}} --output build --configuration Release /warnaserror
      shell: bash
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build
