name: '.NET Core build'
description: 'Build projects with .NET Core'

inputs:
  target-framework:
    description: 'Target .NET framework'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies and build
      run: dotnet build --configuration Release /warnaserror
      shell: bash
    - name: Compress build artifact
      run: tar cvzf build-artifact.tar.gz bin/
      shell: bash
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build-artifact.tar.gz
