name: 'Notification: Fork'

on:
  workflow_dispatch:
  fork:

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on fork
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECIPIENT }}
          token: ${{ secrets.TELEGRAM_BOT_API }}
          message: The '${{ github.actor }}' user fork the repository.
