name: 'Notifications'

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, closed, reopened, ready_for_review, review_requested ]
  issues: 
    types: [ opened, edited, deleted, closed, reopened ]
  fork:
  watch:

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: telegram-notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_API }}
          message: |
            Hello there,
            There is new ${{ github.event_name }} in NClient by ${{ github.actor }}.
