name: 'Release: Beta'

on:
  push:
    branches: beta-release

env:
  solution: NClient.sln
  release-type: beta
  nuget-source: https://api.nuget.org/v3/index.json
      
jobs:
  
  release:
    if: github.ref == 'refs/heads/beta-release'
    environment: release-beta
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - id: release-info
      name: Release info
      uses: ./actions/release-info
      with:
        release-type: ${{ env.release-type }}
    - name: Push packaget to NuGet
      uses: ./actions/push
      with:
        solution: ${{ env.solution }}
        version-prefix: ${{ steps.release-info.outputs.version-prefix }}
        version-suffix: ${{ steps.release-info.outputs.version-suffix }}
        source: ${{ env.nuget-source }}
        source-api-key: ${{ secrets.NUGET_API_KEY }}
        needsTag: true
      
  validation:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - id: release-info
      name: Release info
      uses: ./actions/release-info
      with:
        release-type: ${{ env.release-type }}
    - name: Test release
      uses: ./actions/test-release
      with:
        solution: ${{ env.solution }}
        version-prefix: ${{ steps.release-info.outputs.version-prefix }}
        version-suffix: ${{ steps.release-info.outputs.version-suffix }}
        delay: 5m
