name: 'Release: Alpha'

on:
  push:
    branches: alpha-release

env:
  release-type: alpha
  nuget-source: https://api.nuget.org/v3/index.json
      
jobs:
  
  release:
    if: github.ref == 'refs/heads/alpha-release'
    environment: release-alpha
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - id: release-info
      name: Release info
      uses: ./actions/release-info
      with:
        release-type: ${{ env.release-type }}
    - name: Push packaget to NuGet
      uses: ./actions/push
      with:
        version-prefix: ${{ steps.release-info.outputs.version-prefix }}
        version-suffix: ${{ steps.release-info.outputs.version-suffix }}
        source: ${{ env.nuget-source }}
        source-api-key: ${{ secrets.NUGET_API_KEY }}
        needsTag: true
      
  validation:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - id: release-info
      name: Release info
      uses: ./actions/release-info
      with:
        release-type: ${{ env.release-type }}
    - name: Test release
      uses: ./actions/test-release
      with:
        version-prefix: ${{ steps.release-info.outputs.version-prefix }}
        version-suffix: ${{ steps.release-info.outputs.version-suffix }}
        delay: 5m
