name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build on .NET 5.0
        uses: ./actions/dotnet-core-build
      - name: Test on .NET 5.0
        uses: ./actions/dotnet-core-test
        with:
          target-framework: 'netcoreapp3.1'
