name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
          
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test on .NET 5.0
        uses: ./actions/core-test
        with:
          framework: 'net5.0'
