name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  framework-build:
    strategy:
      matrix:
        target-frameworks: [net462, net472, net48]
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build on MSBuild 16.5
        uses: ./actions/dotnet-build
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: 'Tests.slnf'

  core-build:
    strategy:
      matrix:
        target-frameworks: [netcoreapp3.1, net5.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build on .NET 5.0
        uses: ./actions/dotnet-build
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: 'Tests.slnf'
          
  framework-test:
    needs: framework-build
    strategy:
      matrix:
        os: [windows-latest]
        target-frameworks: [net462, net472, net48]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test on .NET 5.0
        uses: ./actions/dotnet-framework-test
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: 'NClient.sln'
          
  core-test:
    needs: core-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target-frameworks: [netcoreapp3.1, net5.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test on .NET 5.0
        uses: ./actions/dotnet-core-test
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: 'NClient.sln'
