name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        target-frameworks: [netcoreapp3.1, net5.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build on .NET 5.0
        uses: ./actions/dotnet-core-build
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: 'Tests.slnf'
          
  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target-frameworks: [netcoreapp3.1, net5.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test on .NET 5.0
        uses: ./actions/dotnet-core-test
        with:
          target-framework: ${{ matrix.target-frameworks }}
          solution: 'Tests.slnf'
